//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps4KidsWeb.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class App
    {
        public App()
        {
            this.Recentions = new HashSet<Recention>();
            this.Categories = new HashSet<Category>();
            this.Pictures = new HashSet<Picture>();
            this.OperatingSystems = new HashSet<AppOS>();
        }
    
        public int ID { get; set; }
        public int ProducerID { get; set; }
        public string Designation { get; set; }
        public string URL { get; set; }
        public decimal Price { get; set; }
        public string Prerequisites { get; set; }
        public string Description { get; set; }
    
        public virtual Producer Producer { get; set; }
        public virtual ICollection<Recention> Recentions { get; set; }
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<Picture> Pictures { get; set; }
        public virtual ICollection<AppOS> OperatingSystems { get; set; }
    }
}
