//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps4KidsWeb.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryOfOrigin
    {
        public CountryOfOrigin()
        {
            this.Users = new HashSet<User>();
        }
    
        public int ID { get; set; }
        public string Designation { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
