//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps4KidsWeb.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recention
    {
        public int UserID { get; set; }
        public int AppID { get; set; }
        public int Rating { get; set; }
        public string Comment { get; set; }
        public System.DateTime Date { get; set; }
        public int ID { get; set; }
    
        public virtual App App { get; set; }
        public virtual User User { get; set; }
    }
}
