//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps4KidsWeb.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recommendation
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int OSID { get; set; }
        public string AppDesignation { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual AppOS AppOS { get; set; }
        public virtual User User { get; set; }
        public virtual Approved Approved { get; set; }
        public virtual Denied Denied { get; set; }
    }
}
