//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps4KidsWeb.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Recentions = new HashSet<Recention>();
            this.Recommendations = new HashSet<Recommendation>();
        }
    
        public int ID { get; set; }
        public int CountryOfOriginID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EMail { get; set; }
        public string Children { get; set; }
        public byte[] Password { get; set; }
    
        public virtual CountryOfOrigin CountryOfOrigin { get; set; }
        public virtual ICollection<Recention> Recentions { get; set; }
        public virtual Admin Admin { get; set; }
        public virtual AuthentificationCode AuthentificationCode { get; set; }
        public virtual UserLock UserLock { get; set; }
        public virtual ICollection<Recommendation> Recommendations { get; set; }
        public virtual ChangePasswordCode ChangePasswordCode { get; set; }
    }
}
